recipe_sharing/main_app/urls.py
from django.urls import path
from main_app import views

app_name = 'main_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('recipe/<slug:recipe_title_slug>/',
         views.render_recipe, name='render_recipe'),
    #path('register', views.register, name='register'),
    #path('login/', views.user_login, name='login'),
    #path('my-profile/', views.user_profile, name='my-profile'),
    #path('my-profile/saved/', views.profile_saved, name='profile_saved'),
    path('search/', views.search, name='search'),
    #path('submit/', views.submit, name='submit'),
]

recipe_sharing/recipe_sharing/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),    
    path('', include('main_app.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # Trying to get the media to work (so recipes can use their placeholder pics)

recipe_sharing/main_app/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE) # stores username, password, email
    about_me = models.CharField(max_length=256)


    def __str__(self):
        return self.user.username


    class Meta:
        verbose_name_plural = 'UserProfiles'


class Ingredient(models.Model):
    name = models.CharField(max_length=128, unique=True)
    units = models.CharField(max_length=32) #e.g. grams, milliliters
 

    def __str__(self):
        return f"{self.name}, measured in {self.units}"


    class Meta:
        verbose_name_plural = 'Ingredients'


class Tag(models.Model):
    content = models.CharField(max_length=64, unique=True, default="")

    def save(self, *args, **kwargs):
        self.content = self.content.lower()
        super(Tag, self).save(*args, **kwargs)


class Recipe(models.Model):    
    author = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='%(class)s_author_user')    
    users_who_saved = models.ManyToManyField(UserProfile, blank=True, related_name='%(class)s_saved_user')    
    tags = models.ManyToManyField(Tag)
    title = models.CharField(max_length=128)
    title_slug = models.SlugField()
    ingredients = models.ManyToManyField(Ingredient, through='RecipeToIngredient')    
    description = models.CharField(max_length=4096)    
    estimated_nutrition = models.SmallIntegerField(default=1) #Ranges [1-3]
    estimated_price = models.SmallIntegerField(default=1) #Ranges [1-3]
    minutes_to_prepare = models.SmallIntegerField(default=0) 
    picture = models.ImageField(upload_to='recipe_images', blank=True) #Located at "/media/<upload_to>"
            

    def save(self, *args, **kwargs):
        self.title_slug = slugify(self.title)
        super(Recipe, self).save(*args, **kwargs)


    def __str__(self):
        return self.title


    class Meta:
        verbose_name_plural = 'Recipes'


class RecipeToIngredient(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE)
    ingredient_quantity = models.PositiveSmallIntegerField(default=0) #unique for each recipe-ingredient map


    def __str__(self):
        return f"{str(self.ingredient)} for {str(self.recipe)}; quantity: {self.ingredient_quantity}"


class Comment(models.Model):
    content = models.CharField(max_length=4096)
    time_posted = models.DateTimeField(auto_now_add=True) # Save creation timestamp
    parent_comment = models.ForeignKey('self', on_delete=models.CASCADE, null=True)    
    author = models.ForeignKey(UserProfile, on_delete=models.CASCADE) # Consider on_delete SET_DEFAULT
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)


    def __str__(self):
        return f"{self.time_posted} by {str(self.author)} on post {str(self.recipe)}: {self.content}. \n Parent Comment: {str(self.parent_comment)}"


    class Meta:
        verbose_name_plural = 'Comments'

recipe_sharing/main_app/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.urls import reverse
#from main_app.forms import UserForm, UserProfileForm
from django.contrib.auth import authenticate, login
from django.http import HttpResponse, JsonResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from .models import Recipe, Comment


def index(request):
    context_dict = {}
    context_dict["recipes"] = Recipe.objects.all()    
    return render(request, 'main_app/index.html', context=context_dict)


def render_recipe(request, recipe_title_slug):
    context = {"recipe" : None, "comments" : None}
    try:
        context["recipe"] = Recipe.objects.get(title_slug=recipe_title_slug)
    except Recipe.DoesNotExist:
        pass
    context["comments"] = Comment.objects.filter(recipe=context["recipe"]).order_by("time_posted") #Should get all comments which have this recipe as FK
    return render(request, "main_app/recipe.html", context=context)


def about(request):
    context_dict = {}
    context_dict['boldmessage'] = 'This is the about page'

    response = render(request, 'main_app/about.html', context=context_dict)
    return response


def get_filtered_recipes(search_query):
    recipes = None
    ingredients = [i.strip() for i in str.split(search_query, " ") if i != ""]
    substrings = set()    

    for ingredient in ingredients:        
        if ingredient.isalpha() and ingredient not in substrings:            
            if recipes is None:
                recipes = Recipe.objects.filter(recipetoingredient__ingredient__name__istartswith=ingredient).distinct()
            else:
                recipes &= (Recipe.objects.filter(recipetoingredient__ingredient__name__istartswith=ingredient).distinct())            
            
            for i in range(len(ingredient)):
                substrings.add(ingredient[:i+1])
        
    return recipes


def search(request):    
    search_query = "" if "ingredient_input" not in request.GET else request.GET["ingredient_input"]
    recipes = None if search_query=="" else get_filtered_recipes(search_query)
    #print(request.GET)
    #print(recipes)
    return render(request, "main_app/search.html", {"recipes":recipes})


# def register(request):

#     registered = False

#     if request.method =='POST':
#         user_form = UserForm(request.POST)
#         profile_form = UserProfileForm(request.POST)

#         if user_form.is_valid() and profile_form.is_valid():
#             user = user_form.save()

#             user.set_password(user.password)
#             user.save()

#             profile = profile_form.save(commit=False)
#             profile.user = user

#             if 'picture' in request.FILES:
#                 profile.picture = request.FILES['pictures']

#             profile.save()

#             registered = True
#         else:
#             print(user_form.errors, profile_form.errors)
#     else:
#         user_form = UserForm()
#         profile_form = UserProfileForm()

#     return render(request,
#                   'main_app/register.html',
#                   context = {'user_form': user_form,
#                              'profile_form': profile_form,
#                              'registered': registered})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return redirect(reverse('main_app:index'))
            else:
                return HttpResponse("Your Recipe Sharing account is disabled.")
        else:
            print(f"Invalid login details: {username}, {password}")
            return HttpResponse("Invalid login details supplied.")
    else:
        return render(request, 'main_app/login.html')

@login_required
def user_logout(request):
    logout(request)
    return redirect(reverse('rango:index'))

recipe_sharing/templates/main_app/about.html
{% extends "main_app/base.html" %}
{% load staticfiles %}
{% block title_block %}
    About
{% endblock %}

{% block body_block %}
    A recipe sharing site, which allows the users to search for recipes via listing ingredients (that they presumably have).
{% endblock %}

recipe_sharing/templates/main_app/add_recipe.html
{% extends "main_app/base.html" %}
{% block title_block %}
Add a recipe
{% endblock %}
{% block body_block %}
<h1>Add a recipe</h1>
<form id="recipe_form" method="post" action="/main_app/add_recipe/">
{% csrf_token %}
{% for hidden in form.hidden_fields %}
{{ hidden }}
{% endfor %}
{% for field in form.visible_fields %}
{{ field.errors }}
{{ field.help_text }}
{{ field }}
{% endfor %}
<input type="submit" name="submit" value="Create recipe" />
</form>
{% endblock %}

recipe_sharing/templates/main_app/base.html
{% load static %}
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>    
    <link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet"> <!-- Added bootstrap css support -->
    <script src="{% static 'js/bootstrap.min.js'%}"></script> <!-- Added bootstrap js support (all files are in /static/js or css) -->
    <script type="text/javascript" src="{% static 'jquery-3.6.0.min.js' %}"></script> 
    <script type="text/javascript" src="{% static 'main_app-jquery.js' %}"></script>    
<title>
{% block title_block %}
    Base    
{% endblock %}
</title>
</head>
<body>
    <!-- NAVBAR -->
    <nav class="navbar navbar-expand-lg d-flex justify-content-center">               
            <ul class="nav nav-fill d-flex justify-content-">
                <li class="nav-item"><a class="nav-link" href="{% url 'main_app:search' %}">Search</a></li>
                <li class="nav-item"><a class="nav-link disabled">Saved</a></li> <!-- Currently a placeholder, until view works -->
                <a class="navbar-brand display-1" href="{% url 'main_app:index' %}">E-Recipe</a>
                <li class="nav-item"><a class="nav-link disabled">Login</a></li> <!-- Currently a placeholder, until view works -->
                <li class="nav-item"><a class="nav-link" href="{% url 'main_app:about' %}">About</a></li>
            </ul>
    </nav>
    <!-- NAVBAR END -->
{% block body_block %}
{% endblock %}
</body>
</html>

recipe_sharing/templates/main_app/index.html
{% extends "main_app/base.html" %}
{% load staticfiles %}

{% block title_block %}
    Index
{% endblock %}

{% block body_block %}
    <div class="container d-flex justify-content-center flex-column flex-wrap">
            {% if recipes %}
                <ul class="card-group flex-wrap justify-content-evenly">
                {% for recipe in recipes %}
                    <li class="card" style="width: 18rem;min-width: 18rem;max-width 18rem;height: 30rem; overflow:hidden;">
                        <img src="{{recipe.picture.url}}" class="card-img-top" style="max-height:50%"alt="recipe_pic">
                        <div class="card-body"style="max-height:50%">
                            <h5 class="card-title">{{recipe.title}}</h5>
                            <h6 class="card-subtitle mb-2 text-muted">by {{recipe.author}}</h6>
                            <div style="overflow:hidden;max-height:90%;">
                                <p class="card-text"style="display:-webkit-box;max-width:90%;-webkit-line-clamp:5;-webkit-box-orient:vertical;overflow-hidden;">{{recipe.description}}</p>
                            </div>
                            <a href="{% url 'main_app:render_recipe' recipe.title_slug %}" class="btn btn-primary">Go to recipe</a>
                        </div>
                    </li>
                {% endfor %}
                </ul>
            {% else %}
                <strong>No recipes found</strong>
            {% endif %}
    </div>
{% endblock %}

recipe_sharing/templates/main_app/login.html
{% extends 'recipe_sharing/base.html' %}
{% load staticfiles %}
{% block title_block %}
Login
{% endblock %}
{% block body_block %}

<form id="login_form" method="post" action="{% url 'recipe_sharing:login' %}">
{% csrf_token %}
<h4>Username: <input type="text" name="username" value="" size="100" /></h4>

<h4>Password:  <input type="password" name="password" value="" size="100" /></h6>

<input type="submit" value="submit" />
</form>
{% endblock %}

recipe_sharing/templates/main_app/my-profile.html
{% extends 'recipe_sharing/base.html' %}
{% load staticfiles %}
{% block title_block %}
Homepage
{% endblock %}
{% block body_block %}
<div>
{% if user.is_authenticated %}
{{ user.username }}!
{% else %}
ERROR
{% endif %}
</div>
<div>
    <h2>Saved Recipes</h2>
        {% if recipes %}
            <div>
                {% for recipe in recipes %}
                    <div>
                        <li><a href="{% url 'show_recipe' recipe.slug %}">{{ recipe.name }}</a></li>
                    </div>
                {% endfor %}
            </div>
        {% else %}
        <strong>There are no pages present.</strong>'
        {% endif %}
</div>
{% endblock %}

recipe_sharing/templates/main_app/recipe.html
{% extends 'main_app/base.html' %}
{% load staticfiles %}

{% block title_block %}

{% endblock %}

{% block body_block %}
<div class="container-fluid"> <!-- Entire dish page div -->
    {% if recipe %}
        <h2 class="display-3">{{ recipe.title }}</h2>
        <p class="text-muted"> by {{ recipe.author }}</p>  
        <ul class="list-group list-group-horizontal">
            <li class="list-group-item">⌚ {{ recipe.minutes_to_prepare }}  mins</li>
            <li class="list-group-item">£ {{ recipe.estimated_price }} / 3</li>
            <li class="list-group-item">𓇣 {{ recipe.estimated_nutrition}} / 3</li>
        </ul>
    {% else %}
        Unknown recipe
    {% endif %}

    {% if recipe.picture %}
        <div style="display:flex;">
            <img src="{{recipe.picture.url}}" alt="recipe_picture" style="max-width:100%">
        </div>
    {% endif %}

    {% if recipe.recipetoingredient_set.all%}
        <h5 class="display-6"> This recipe contains the following ingredients: </h3>
        {% for map in recipe.recipetoingredient_set.all %}
        <ul class="list-group d-flex flex-wrap" style="max-width: 7%">
            <li class="list-group-item">{{ map.ingredient.name }}  <small class="text-muted">  {{ map.ingredient_quantity }} {{ map.ingredient.units }}</small></li>
        </ul>
        {% endfor %}
        </ul>
    {% else %}
         <li><strong>Recipe has no attached ingredients present.</strong></li>
    {% endif %}
    </ul>

    <h5 class="display-6">Instructions:</h5>
    <p>{{ recipe.description }}</p>

    {% if recipe.tags.all%}
    <h5 class="display-6">Tags:</h2>
    <ul style="list-style: none">
    {% for tag in recipe.tags.all %}
        <li>#{{ tag.content }} </a></li>
    {% endfor %}
    </ul>
    {% else %}
    <h2> This recipe has no attached tags.</h2>
    {% endif %}
    
    
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link active" aria-current="page">Comments</a>
        </li>
        <li class="nav-item">
            <a class="nav-link disabled" aria-disabled="true">Add comment</a>
        </li>
    </ul>
    {% if comments %}
        {% for comment in comments %}
        <div class="container border rounded" style="margin-bottom:2.5px;margin-top:2.5px">
            <span class="badge rounded-pill bg-success">{{comment.author}}</span><p class="text-muted">{{comment.time_posted}}</p>
            <p>{{comment.content}}</p>
        </div>
        {% endfor %}
    {% else %}
        <p style="padding-left:0.5%"> There are no comments </p>
    {% endif %}
</div> <!-- end of dish page div -->
{% endblock %}

recipe_sharing/templates/main_app/restricted.html
{% extends 'recipe_sharing/base.html' %}

{% block title_block %}
    Restricted Page
{% endblock %}

{% block body_block %}
<h1>Restricted Page</h1>
{% endblock %} 

recipe_sharing/templates/main_app/search.html
{% extends 'main_app/base.html' %}
{% block title_block %}
{% endblock %}

{% block body_block %}
<div id="search_div" style="display:flex; justify-content:right; padding:1.5%">
    <input  id="ingredient_input" type="text" name="ingredient_input"  placeholder="Input space separated ingredients..." >
</div>

<div id="recipe_search_results" style="height:auto">
    <ul class="container-xs d-flex flex-row flex-wrap justify-content-left"> <!-- unordered list of "Card" bstrap objs -->
    {% if recipes %}                
        {% for recipe in recipes %}    
            <li class="card" style="width: 18rem;">
                <img src="{{recipe.picture.url}}" class="card-img-top" alt="recipe_pic">  
                <div class="card-body">
                    <h5 class="card-title"> <a href="{% url 'main_app:render_recipe' recipe.title_slug %}">{{ recipe.title }}</a> </h5>
                </div>
                <ul class="list-group list-group-flush">           
            {% for map in recipe.recipetoingredient_set.all %}
                    <li class="list-group-item">{{ map.ingredient.name }}: {{ map.ingredient_quantity }} {{ map.ingredient.units }}</li>
            {% endfor %}
            </li>
        {% endfor %}        
    {% else %}
        No recipe results
    {% endif %}
    </ul> <!-- end of card list -->
</div>

{% endblock %}

recipe_sharing/templates/main_app/submit.html
{% extends 'recipe_sharing/base.html' %}
{% load staticfiles %}
{% block title_block %}
Register
{% endblock %}
{% block body_block %}
{% if registered %}
<strong>thank you for registering!</strong>
<a href="{% url 'recipe_sharing:index' %}">Return to the homepage.</a><br />
{% else %}
<strong>register here!</strong><br />
<form id="user_form" method="post" action="{% url 'recipe_sharing:register' %}"
enctype="multipart/form-data">
{% csrf_token %}
{{ user_form.as_p }}
{{ profile_form.as_p }}
<input type="submit" name="submit" value="Register" />
</form>
{% endif %}
{% endblock %}

recipe_sharing/templates/main_app/user.html
{% extends 'recipe_sharing/base.html' %}
{% load staticfiles %}
{% block title_block %}
Homepage
{% endblock %}
{% block body_block %}
<div>
{% if user.is_authenticated %}
{{ user.username }}!
{% else %}
ERROR
{% endif %}
</div>
<div>
{% if recipes %}
<ul>
    {% for recipe in recipes %}
    <li><a href="/{{ user.username }}/{{ recipe.slug }}/">{{ recipe.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
<strong>There are no recipes present.</strong>
{% endif %}
</div>
{% endblock %}

recipe_sharing/templates/recipe_sharing/add_recipe.html
{% extends "recipe_sharing/base.html" %}
{% block title_block %}
Add a recipe
{% endblock %}
{% block body_block %}
<h1>Add a recipe</h1>
<form id="recipe_form" method="post" action="/recipe_sharing/add_recipe/">
{% csrf_token %}
{% for hidden in form.hidden_fields %}
{{ hidden }}
{% endfor %}
{% for field in form.visible_fields %}
{{ field.errors }}
{{ field.help_text }}
{{ field }}
{% endfor %}
<input type="submit" name="submit" value="Create recipe" />
</form>
{% endblock %}

recipe_sharing/templates/recipe_sharing/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load project_template_tags %} 
<html>
<head>
<title>
{% block title_block %}
Website Templates
{% endblock %}
</title>
</head>
<body>

{% block body_block %}
{% endblock %}


</body>
</html>